;;; shrink-whitespace-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from shrink-whitespace.el

(autoload 'shrink-whitespace "shrink-whitespace" "\
Remove whitespace around cursor to just one or none.
If current line contains non-white space chars, then shrink any
whitespace char surrounding cursor to just one space.  If current
line does not contain non-white space chars, then remove blank
lines to just one.
Argument ARG Prevents removal of newlines when no other whitespace exists.

(fn ARG)" t)
(autoload 'shrink-whitespace-grow-whitespace-around "shrink-whitespace" "\
Counterpart to 'shrink-whitespace', grow whitespace in a smartish way." t)
(autoload 'shrink-whitespace-shrink-whitespace-around "shrink-whitespace" "\
Shrink whitespace surrounding point." t)
(register-definition-prefixes "shrink-whitespace" '("grow-whitespace-around" "shrink-whitespace-"))

;;; End of scraped data

(provide 'shrink-whitespace-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; shrink-whitespace-autoloads.el ends here
